let meals= [
    {
        "idMeal": "52812",
        "strMeal": "Beef Brisket Pot Roast",
        "strDrinkAlternate": null,
        "strCategory": "Beef",
        "strArea": "American",
        "strInstructions": "1 Prepare the brisket for cooking: On one side of the brisket there should be a layer of fat, which you want. If there are any large chunks of fat, cut them off and discard them. Large pieces of fat will not be able to render out completely.\r\nUsing a sharp knife, score the fat in parallel lines, about 3/4-inch apart. Slice through the fat, not the beef. Repeat in the opposite direction to make a cross-hatch pattern.\r\nSalt the brisket well and let it sit at room temperature for 30 minutes.\r\n \r\n2 Sear the brisket: You'll need an oven-proof, thick-bottomed pot with a cover, or Dutch oven, that is just wide enough to hold the brisket roast with a little room for the onions.\r\nPat the brisket dry and place it, fatty side down, into the pot and place it on medium high heat. Cook for 5-8 minutes, lightly sizzling, until the fat side is nicely browned. (If the roast seems to be cooking too fast, turn the heat down to medium. You want a steady sizzle, not a raging sear.)\r\nTurn the brisket over and cook for a few minutes more to brown the other side.\r\n\r\n3 Sauté the onions and garlic: When the brisket has browned, remove it from the pot and set aside. There should be a couple tablespoons of fat rendered in the pot, if not, add some olive oil.\r\nAdd the chopped onions and increase the heat to high. Sprinkle a little salt on the onions. Sauté, stirring often, until the onions are lightly browned, 5-8 minutes. Stir in the garlic and cook 1-2 more minutes.\r\n \r\n4 Return brisket to pot, add herbs, stock, bring to simmer, cover, cook in oven: Preheat the oven to 300°F. Use kitchen twine to tie together the bay leaves, rosemary and thyme.\r\nMove the onions and garlic to the sides of the pot and nestle the brisket inside. Add the beef stock and the tied-up herbs. Bring the stock to a boil on the stovetop.\r\nCover the pot, place the pot in the 300°F oven and cook for 3 hours. Carefully flip the brisket every hour so it cooks evenly.\r\n \r\n5 Add carrots, continue to cook: After 3 hours, add the carrots. Cover the pot and cook for 1 hour more, or until the carrots are cooked through and the brisket is falling-apart tender.\r\n6 Remove brisket to cutting board, tent with foil: When the brisket is falling-apart tender, take the pot out of the oven and remove the brisket to a cutting board. Cover it with foil. Pull out and discard the herbs.\r\n7 Make sauce (optional): At this point you have two options. You can serve as is, or you can make a sauce with the drippings and some of the onions. If you serve as is, skip this step.\r\nTo make a sauce, remove the carrots and half of the onions, set aside and cover them with foil. Pour the ingredients that are remaining into the pot into a blender, and purée until smooth. If you want, add 1 tablespoon of mustard to the mix. Put into a small pot and keep warm.\r\n8 Slice the meat across the grain: Notice the lines of the muscle fibers of the roast. This is the \"grain\" of the meat. Slice the meat perpendicular to these lines, or across the grain (cutting this way further tenderizes the meat), in 1/4-inch to 1/2-inch slices.\r\nServe with the onions, carrots and gravy. Serve with mashed, roasted or boiled potatoes, egg noodles or polenta.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg",
        "strTags": "Meat",
        "strYoutube": "https://www.youtube.com/watch?v=gh48wM6bPWQ",
        "strIngredient1": "Beef Brisket",
        "strIngredient2": "Salt",
        "strIngredient3": "Onion",
        "strIngredient4": "Garlic",
        "strIngredient5": "Thyme",
        "strIngredient6": "Rosemary",
        "strIngredient7": "Bay Leaves",
        "strIngredient8": "beef stock",
        "strIngredient9": "Carrots",
        "strIngredient10": "Mustard",
        "strIngredient11": "Potatoes",
        "strIngredient12": null,
        "strIngredient13": null,
        "strIngredient14": null,
        "strIngredient15": null,
        "strIngredient16": null,
        "strIngredient17": null,
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "4-5 pound",
        "strMeasure2": "Dash",
        "strMeasure3": "3",
        "strMeasure4": "5 cloves",
        "strMeasure5": "1 Sprig",
        "strMeasure6": "1 sprig ",
        "strMeasure7": "4",
        "strMeasure8": "2 cups",
        "strMeasure9": "3 Large",
        "strMeasure10": "1 Tbsp",
        "strMeasure11": "4 Mashed",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http://www.simplyrecipes.com/recipes/beef_brisket_pot_roast/",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52880",
        "strMeal": "McSinghs Scotch pie",
        "strDrinkAlternate": null,
        "strCategory": "Lamb",
        "strArea": "British",
        "strInstructions": "Heat a large frying pan and toast the cumin seeds for a few minutes, then set aside. Heat the oil in the same pan and fry the onion, garlic, chilli, pepper and a good pinch of salt for around eight minutes, until there is no moisture left. Remove from the heat, stir in the toasted cumin seeds, ground mace (or nutmeg) and ground coriander. Leave to cool.\r\nIn a large bowl mix together the minced lamb, white pepper, fresh coriander, and the cooled spiced onion mixture until combined. Set aside, covered, in the fridge.\r\nPreheat the oven to 200C/400F/Gas 6 and generously grease a 20cm/8in diameter loose-bottomed or springform round cake tin with lard.\r\nTo make the pastry, sift the flour and salt in a large bowl and make a well in the centre.\r\nPut the milk, lard and 90ml/3fl oz of water in a saucepan and heat gently. When the lard has melted, increase the heat and bring to the boil.\r\nPour the boiling liquid into the flour, and use a wooden spoon to combine until cool enough to handle. Bring together into a ball.\r\nDust a work surface with flour and, working quickly, knead the dough briefly – it will be soft and moist. Set aside a third of the pastry and roll the rest out on a well-floured surface. Line the pie dish with the pastry, pressing it right up the sides until it pokes just over the top of the tin.\r\nAdd the filling into the pastry-lined tin bit by bit. As you reach the top, form a slight peak. Roll out the reserved pastry and top the pie with it. Pinch the edges to seal and trim the excess. Poke a hole in the top of the pie and insert a small tube made from aluminium foil to allow steam to escape.\r\nBrush the top of the pie with a little beaten egg yolk, and bake in the preheated oven for 30 minutes (put a tray on the shelf below to catch any drips). Then reduce the temperature to 160C/325F/Gas 3 and cook for a further 1¼ hours until golden-brown. Leave to cool completely before refrigerating for two hours, or overnight.\r\nRun a knife around the edge of the pie, remove from the tin and serve with chutneys, salads or pickles.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/vssrtx1511557680.jpg",
        "strTags": "Pie",
        "strYoutube": "https://www.youtube.com/watch?v=1nArqhRyszw",
        "strIngredient1": "Cumin",
        "strIngredient2": "Rapeseed Oil",
        "strIngredient3": "Red Onions",
        "strIngredient4": "Garlic Clove",
        "strIngredient5": "Green Chilli",
        "strIngredient6": "Red Pepper",
        "strIngredient7": "Nutmeg",
        "strIngredient8": "Coriander",
        "strIngredient9": "Lamb Mince",
        "strIngredient10": "Pepper",
        "strIngredient11": "Coriander",
        "strIngredient12": "Plain Flour",
        "strIngredient13": "Salt",
        "strIngredient14": "Milk",
        "strIngredient15": "Lard",
        "strIngredient16": "Egg Yolks",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "2 tsp",
        "strMeasure2": "1 tbs",
        "strMeasure3": "2 finely chopped",
        "strMeasure4": "6",
        "strMeasure5": "3 finely chopped",
        "strMeasure6": "1 finely chopped ",
        "strMeasure7": "1 tsp ",
        "strMeasure8": "2 tsp",
        "strMeasure9": "1kg",
        "strMeasure10": "1 tsp ",
        "strMeasure11": "3 tbs",
        "strMeasure12": "340g",
        "strMeasure13": "½ tsp",
        "strMeasure14": "90 ml ",
        "strMeasure15": "150g",
        "strMeasure16": "Beaten",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://www.bbc.co.uk/food/recipes/mcsinghs_scotch_pie_98356",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52767",
        "strMeal": "Bakewell tart",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "To make the pastry, measure the flour into a bowl and rub in the butter with your fingertips until the mixture resembles fine breadcrumbs. Add the water, mixing to form a soft dough.\r\nRoll out the dough on a lightly floured work surface and use to line a 20cm/8in flan tin. Leave in the fridge to chill for 30 minutes.\r\nPreheat the oven to 200C/400F/Gas 6 (180C fan).\r\nLine the pastry case with foil and fill with baking beans. Bake blind for about 15 minutes, then remove the beans and foil and cook for a further five minutes to dry out the base.\r\nFor the filing, spread the base of the flan generously with raspberry jam.\r\nMelt the butter in a pan, take off the heat and then stir in the sugar. Add ground almonds, egg and almond extract. Pour into the flan tin and sprinkle over the flaked almonds.\r\nBake for about 35 minutes. If the almonds seem to be browning too quickly, cover the tart loosely with foil to prevent them burning.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg",
        "strTags": "Tart,Baking,Alcoholic",
        "strYoutube": "https://www.youtube.com/watch?v=1ahpSTf_Pvk",
        "strIngredient1": "plain flour",
        "strIngredient2": "chilled butter",
        "strIngredient3": "cold water",
        "strIngredient4": "raspberry jam",
        "strIngredient5": "butter",
        "strIngredient6": "caster sugar",
        "strIngredient7": "ground almonds",
        "strIngredient8": "free-range egg, beaten",
        "strIngredient9": "almond extract",
        "strIngredient10": "flaked almonds",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": null,
        "strIngredient17": null,
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "175g/6oz",
        "strMeasure2": "75g/2½oz",
        "strMeasure3": "2-3 tbsp",
        "strMeasure4": "1 tbsp",
        "strMeasure5": "125g/4½oz",
        "strMeasure6": "125g/4½oz",
        "strMeasure7": "125g/4½oz",
        "strMeasure8": "1",
        "strMeasure9": "½ tsp",
        "strMeasure10": "50g/1¾oz",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": null,
        "strMeasure17": null,
        "strMeasure18": null,
        "strMeasure19": null,
        "strMeasure20": null,
        "strSource": null,
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52792",
        "strMeal": "Bread and Butter Pudding",
        "strDrinkAlternate": null,
        "strCategory": "Dessert",
        "strArea": "British",
        "strInstructions": "Grease a 1 litre/2 pint pie dish with butter.\r\nCut the crusts off the bread. Spread each slice with on one side with butter, then cut into triangles.\r\nArrange a layer of bread, buttered-side up, in the bottom of the dish, then add a layer of sultanas. Sprinkle with a little cinnamon, then repeat the layers of bread and sultanas, sprinkling with cinnamon, until you have used up all of the bread. Finish with a layer of bread, then set aside.\r\nGently warm the milk and cream in a pan over a low heat to scalding point. Don't let it boil.\r\nCrack the eggs into a bowl, add three quarters of the sugar and lightly whisk until pale.\r\nAdd the warm milk and cream mixture and stir well, then strain the custard into a bowl.\r\nPour the custard over the prepared bread layers and sprinkle with nutmeg and the remaining sugar and leave to stand for 30 minutes.\r\nPreheat the oven to 180C/355F/Gas 4.\r\nPlace the dish into the oven and bake for 30-40 minutes, or until the custard has set and the top is golden-brown.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/xqwwpy1483908697.jpg",
        "strTags": "Pudding,Brunch",
        "strYoutube": "https://www.youtube.com/watch?v=Vz5W1-BmOE4",
        "strIngredient1": "butter",
        "strIngredient2": "bread",
        "strIngredient3": "sultanas",
        "strIngredient4": "cinnamon",
        "strIngredient5": "milk",
        "strIngredient6": "double cream",
        "strIngredient7": "eggs",
        "strIngredient8": "sugar",
        "strIngredient9": "nutmeg",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "25g/1oz",
        "strMeasure2": "8 thin slices",
        "strMeasure3": "50g/2oz",
        "strMeasure4": "2 tsp",
        "strMeasure5": "350ml/12fl",
        "strMeasure6": "50ml/2fl oz",
        "strMeasure7": "2 free-range",
        "strMeasure8": "25g/1oz",
        "strMeasure9": "grated, to taste",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://cooking.nytimes.com/recipes/1018529-coq-au-vin",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    },
    {
        "idMeal": "52803",
        "strMeal": "Beef Wellington",
        "strDrinkAlternate": null,
        "strCategory": "Beef",
        "strArea": "British",
        "strInstructions": "Put the mushrooms into a food processor with some seasoning and pulse to a rough paste. Scrape the paste into a pan and cook over a high heat for about 10 mins, tossing frequently, to cook out the moisture from the mushrooms. Spread out on a plate to cool.\r\nHeat in a frying pan and add a little olive oil. Season the beef and sear in the hot pan for 30 secs only on each side. (You don't want to cook it at this stage, just colour it). Remove the beef from the pan and leave to cool, then brush all over with the mustard.\r\nLay a sheet of cling film on a work surface and arrange the Parma ham slices on it, in slightly overlapping rows. With a palette knife, spread the mushroom paste over the ham, then place the seared beef fillet in the middle. Keeping a tight hold of the cling film from the edge, neatly roll the Parma ham and mushrooms around the beef to form a tight barrel shape. Twist the ends of the cling film to secure. Chill for 15-20 mins to allow the beef to set and keep its shape.\r\nRoll out the puff pastry on a floured surface to a large rectangle, the thickness of a £1 coin. Remove the cling film from the beef, then lay in the centre. Brush the surrounding pastry with egg yolk. Fold the ends over, the wrap the pastry around the beef, cutting off any excess. Turn over, so the seam is underneath, and place on a baking sheet. Brush over all the pastry with egg and chill for about 15 mins to let the pastry rest.\r\nHeat the oven to 200C, 400F, gas 6.\r\nLightly score the pastry at 1cm intervals and glaze again with beaten egg yolk. Bake for 20 minutes, then lower the oven setting to 180C, 350F, gas 4 and cook for another 15 mins. Allow to rest for 10-15 mins before slicing and serving with the side dishes of your choice. The beef should still be pink in the centre when you serve it.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
        "strTags": "Meat,Stew",
        "strYoutube": "https://www.youtube.com/watch?v=FS8u1RBdf6I",
        "strIngredient1": "mushrooms",
        "strIngredient2": "English Mustard",
        "strIngredient3": "Olive Oil",
        "strIngredient4": "Beef Fillet",
        "strIngredient5": "Parma ham",
        "strIngredient6": "Puff Pastry",
        "strIngredient7": "Flour",
        "strIngredient8": "Egg Yolks",
        "strIngredient9": null,
        "strIngredient10": null,
        "strIngredient11": null,
        "strIngredient12": null,
        "strIngredient13": null,
        "strIngredient14": null,
        "strIngredient15": null,
        "strIngredient16": null,
        "strIngredient17": null,
        "strIngredient18": null,
        "strIngredient19": null,
        "strIngredient20": null,
        "strMeasure1": "400g",
        "strMeasure2": "1-2tbsp",
        "strMeasure3": "Dash",
        "strMeasure4": "750g piece",
        "strMeasure5": "6-8 slices",
        "strMeasure6": "500g",
        "strMeasure7": "Dusting",
        "strMeasure8": "2 Beaten ",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "strMeasure16": "",
        "strMeasure17": "",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "http://www.goodtoknow.co.uk/recipes/164868/Gordon-Ramsay-s-beef-Wellington",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }
]

export default meals